[package]
name = "pigeon-backend"
version = "0.1.0"
authors = ["David Cao <david@cao.st>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
diesel = "1.4"
dotenv = "0.12"

[lib]
name = "pigeon_backend"
path = "src/lib.rs"

[[bin]]
name = "pigeon-backend"
path = "src/bin.rs"
